### ISSUE TITLE
Vendor in :linked_dirs

### ISSUE THREAD

**Issue by svondervoort** [dyerc/capistrano-craft#3]
We we're wondering the reason behind the `vendor` folder being in the `:linked_dirs`. ([source](https://github.com/dyerc/capistrano-craft/blob/master/lib/capistrano/craft/defaults.rb#L5))
Could you elaborate?

**Comment by dyerc** [comment]
It's my understanding that when `composer install` runs on each deploy, the dependencies in the `composer.json` file will be checked against the `vendor` folder. Since some dependencies won't change every deploy, I put the `vendor` folder as linked so that composer isn't downloading the same packages again and again each time.

**Comment by svondervoort** [comment]
Understandable.

At the moment we are encountering an issue with one of the packages on `composer install` saying there are `uncomitted changes` (git). So in this case we used `remove :linked_dirs, "vendor"` in our deploy.rb to overwrite your settings.
